mongo:
  connectionUrl: mongodb://localhost:27017/gift
  reconnectInterval: 1000
email:
  shouldSendConfirmation: true
  use: server
  server:
    service: gmail
    user: afrikinvest.dev@gmail.com
    pass: necffbjcknmhyeuu
  mailhog:
    host: localhost
    port: 1025
    secure: false
  expirationTime: 86400
  baseURL : http://192.168.116.120:5000
  verificationBaseURL: http://192.168.116.120:5000/verification
login:
  secretKey: XXXXXX
  tokenExpiry: 20000
service:
  verifyToken: false
  api:
    port: 5000
